In [2]:
import requests
from io import BytesIO
from zipfile import ZipFile
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [3]:
# Get the current working directory
current_directory = os.getcwd()

# Print the current directory
print(current_directory)

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\notebooks

In [4]:

# Specify the new directory path (replace with your desired path)
new_directory = r"C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src"


# Change the current working directory to the new path
os.chdir(new_directory)

# Verify the change by printing the new working directory
print("New working directory:", os.getcwd())

New working directory: C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src

In [5]:
p12 = pd.read_csv(r"../data/interim/p12_clean.csv", low_memory=True)

In [6]:
p12.shape

(25299, 75)

In [7]:
second_day = p12[160:449] ## 288 -> 737
third_day = p12[449:737]
fourth_day = p12[449:1025] #288

fourth_day

,p_num,time,bg-5:55,bg-5:50,bg-5:45,bg-5:40,bg-5:35,bg-5:30,bg-5:25,bg-5:20,...,bg-0:40,bg-0:35,bg-0:30,bg-0:25,bg-0:20,bg-0:15,bg-0:10,bg-0:05,bg-0:00,bg+1:00
449,p12,00:05:00,15.3,15.3,15.0,14.9,15.0,14.8,13.7,12.6,...,4.4,4.8,5.0,5.0,5.0,4.9,4.8,4.9,5.1,6.9
450,p12,00:10:00,15.3,15.0,14.9,15.0,14.8,13.7,12.6,12.1,...,4.8,5.0,5.0,5.0,4.9,4.8,4.9,5.1,5.5,6.9
451,p12,00:15:00,15.0,14.9,15.0,14.8,13.7,12.6,12.1,11.3,...,5.0,5.0,5.0,4.9,4.8,4.9,5.1,5.5,5.9,7.2
452,p12,00:20:00,14.9,15.0,14.8,13.7,12.6,12.1,11.3,10.6,...,5.0,5.0,4.9,4.8,4.9,5.1,5.5,5.9,6.2,7.4
453,p12,00:25:00,15.0,14.8,13.7,12.6,12.1,11.3,10.6,10.5,...,5.0,4.9,4.8,4.9,5.1,5.5,5.9,6.2,6.3,7.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,p12,23:40:00,13.4,13.8,14.0,14.4,14.7,14.4,13.9,13.9,...,8.3,8.2,8.3,8.5,8.7,9.3,9.9,10.4,10.5,11.7
1021,p12,23:45:00,13.8,14.0,14.4,14.7,14.4,13.9,13.9,13.5,...,8.2,8.3,8.5,8.7,9.3,9.9,10.4,10.5,10.9,11.2
1022,p12,23:50:00,14.0,14.4,14.7,14.4,13.9,13.9,13.5,13.2,...,8.3,8.5,8.7,9.3,9.9,10.4,10.5,10.9,11.3,10.7
1023,p12,23:55:00,14.4,14.7,14.4,13.9,13.9,13.5,13.2,12.7,...,8.5,8.7,9.3,9.9,10.4,10.5,10.9,11.3,11.2,10.5
1024,p12,00:00:00,14.7,14.4,13.9,13.9,13.5,13.2,12.7,11.9,...,8.7,9.3,9.9,10.4,10.5,10.9,11.3,11.2,11.5,10.0

In [8]:
p12[161:165]

,p_num,time,bg-5:55,bg-5:50,bg-5:45,bg-5:40,bg-5:35,bg-5:30,bg-5:25,bg-5:20,...,bg-0:40,bg-0:35,bg-0:30,bg-0:25,bg-0:20,bg-0:15,bg-0:10,bg-0:05,bg-0:00,bg+1:00
161,p12,00:05:00,6.0,6.1,6.1,6.0,6.1,6.1,6.0,6.1,...,11.0,11.3,11.7,11.9,12.5,13.0,13.5,13.8,13.9,10.0
162,p12,00:10:00,6.1,6.1,6.0,6.1,6.1,6.0,6.1,6.1,...,11.3,11.7,11.9,12.5,13.0,13.5,13.8,13.9,13.7,10.0
163,p12,00:15:00,6.1,6.0,6.1,6.1,6.0,6.1,6.1,6.1,...,11.7,11.9,12.5,13.0,13.5,13.8,13.9,13.7,13.5,10.3
164,p12,00:20:00,6.0,6.1,6.1,6.0,6.1,6.1,6.1,6.0,...,11.9,12.5,13.0,13.5,13.8,13.9,13.7,13.5,13.3,10.1

In [32]:
from utils import transform_into_ts_preserved_with_date, remove_redundancy, transform_into_ts_preserved
from datetime import datetime, timedelta

def get_day(dataframe):
    # Create an empty list to store each 'day'

    new_date = '2024-10-03'

    # Iterate over the DataFrame in steps of 288, transform it to a time series and save it as csv
    for i in range(160, 25299, 288):
        days = []
        cleaned_df = pd.DataFrame()
        transformed = pd.DataFrame()
        result = pd.DataFrame()
        
        print(i)
        tmp_day = dataframe[i:i+288]  # Get a single row (or slice the day as needed)
        days.append(tmp_day)
        result = pd.concat(days, ignore_index=True)

        # Convert the string to a datetime object
        try:
            new_date = datetime.strptime(new_date, '%Y-%m-%d')
        except:
            pass
        # Add one day using timedelta
        #new_date_plus_one = new_date + timedelta(days=1)
        
        # Convert the datetime object back to a string if needed
        #new_date_plus_one_str = new_date_plus_one.strftime('%Y-%m-%d')
        
        #transformed = transform_into_ts_preserved(result, start_date)
        transformed = transform_into_ts_preserved(result)# , new_date_plus_one_str)
        print(transformed)
        cleaned_df = remove_redundancy(transformed)
        print(cleaned_df)

        cleaned_df.to_csv(f'../data/processed/all_days_p12/p12_{i}_day.csv', index=False)  # Save to a CSV file
        print("shape cleaned")
        print(cleaned_df.shape)
        #print("shape result")
        #print(result.shape)
    
    return result

# # Example usage
day_two = get_day(p12)

160

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 00:00:00  13.8
1     2024-10-02 23:55:00  13.5
2     2024-10-02 23:50:00  13.0
3     2024-10-02 23:45:00  12.5
4     2024-10-02 23:40:00  11.9
...                   ...   ...
20731 2024-10-02 18:20:00  15.0
20732 2024-10-02 18:15:00  15.3
20733 2024-10-02 18:10:00  15.3
20734 2024-10-02 18:05:00  15.1
20735 2024-10-02 18:00:00  15.1

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  13.8
1   2024-10-02 00:05:00  13.9
2   2024-10-02 00:10:00  13.7
3   2024-10-02 00:15:00  13.5
4   2024-10-02 00:20:00  13.3
..                  ...   ...
283 2024-10-02 23:35:00  11.7
284 2024-10-02 23:40:00  11.9
285 2024-10-02 23:45:00  12.5
286 2024-10-02 23:50:00  13.0
287 2024-10-02 23:55:00  13.5

[288 rows x 2 columns]
shape cleaned
(288, 2)
448

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 00:00:00  4.9
1     2024-10-02 23:55:00  4.8
2     2024-10-02 23:50:00  4.9
3     2024-10-02 23:45:00  5.0
4     2024-10-02 23:40:00  5.0
...                   ...  ...
20731 2024-10-02 18:20:00  5.4
20732 2024-10-02 18:15:00  5.3
20733 2024-10-02 18:10:00  5.2
20734 2024-10-02 18:05:00  5.2
20735 2024-10-02 18:00:00  5.2

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  4.9
1   2024-10-02 00:05:00  5.1
2   2024-10-02 00:10:00  5.5
3   2024-10-02 00:15:00  5.9
4   2024-10-02 00:20:00  6.2
..                  ...  ...
283 2024-10-02 23:35:00  5.0
284 2024-10-02 23:40:00  5.0
285 2024-10-02 23:45:00  5.0
286 2024-10-02 23:50:00  4.9
287 2024-10-02 23:55:00  4.8

[288 rows x 2 columns]
shape cleaned
(288, 2)
736

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 00:00:00   9.6
1     2024-10-02 23:55:00   8.8
2     2024-10-02 23:50:00   7.9
3     2024-10-02 23:45:00   7.5
4     2024-10-02 23:40:00   7.3
...                   ...   ...
20731 2024-10-02 18:20:00  13.9
20732 2024-10-02 18:15:00  13.9
20733 2024-10-02 18:10:00  14.4
20734 2024-10-02 18:05:00  14.7
20735 2024-10-02 18:00:00  14.4

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00   9.6
1   2024-10-02 00:05:00  10.5
2   2024-10-02 00:10:00  11.3
3   2024-10-02 00:15:00  11.7
4   2024-10-02 00:20:00  11.6
..                  ...   ...
283 2024-10-02 23:35:00   6.7
284 2024-10-02 23:40:00   7.3
285 2024-10-02 23:45:00   7.5
286 2024-10-02 23:50:00   7.9
287 2024-10-02 23:55:00   8.8

[288 rows x 2 columns]
shape cleaned
(288, 2)
1024

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 00:00:00  11.5
1     2024-10-02 23:55:00  11.2
2     2024-10-02 23:50:00  11.3
3     2024-10-02 23:45:00  10.9
4     2024-10-02 23:40:00  10.5
...                   ...   ...
20731 2024-10-02 21:05:00   NaN
20732 2024-10-02 21:00:00   NaN
20733 2024-10-02 20:55:00   NaN
20734 2024-10-02 20:50:00   NaN
20735 2024-10-02 20:45:00   NaN

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  11.5
1   2024-10-02 00:05:00  11.9
2   2024-10-02 00:10:00  12.3
3   2024-10-02 00:15:00  12.5
4   2024-10-02 00:20:00  12.4
..                  ...   ...
283 2024-10-02 23:35:00  14.2
284 2024-10-02 23:40:00  10.5
285 2024-10-02 23:45:00  14.2
286 2024-10-02 23:50:00  11.3
287 2024-10-02 23:55:00  14.2

[288 rows x 2 columns]
shape cleaned
(288, 2)
1312

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 02:45:00  16.0
1     2024-10-02 02:40:00  16.0
2     2024-10-02 02:35:00  16.4
3     2024-10-02 02:30:00  16.4
4     2024-10-02 02:25:00  16.3
...                   ...   ...
20731 2024-10-02 21:05:00   8.5
20732 2024-10-02 21:00:00   8.3
20733 2024-10-02 20:55:00   7.9
20734 2024-10-02 20:50:00   7.6
20735 2024-10-02 20:45:00   7.3

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  14.4
1   2024-10-02 00:05:00  14.8
2   2024-10-02 00:10:00  14.4
3   2024-10-02 00:15:00   5.9
4   2024-10-02 00:20:00  14.0
..                  ...   ...
283 2024-10-02 23:35:00  14.2
284 2024-10-02 23:40:00   7.3
285 2024-10-02 23:45:00  14.2
286 2024-10-02 23:50:00  14.0
287 2024-10-02 23:55:00  14.2

[288 rows x 2 columns]
shape cleaned
(288, 2)
1600

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 02:45:00   6.7
1     2024-10-02 02:40:00   6.8
2     2024-10-02 02:35:00   6.8
3     2024-10-02 02:30:00   6.8
4     2024-10-02 02:25:00   6.9
...                   ...   ...
20731 2024-10-02 21:05:00  15.3
20732 2024-10-02 21:00:00  15.6
20733 2024-10-02 20:55:00  15.9
20734 2024-10-02 20:50:00  15.9
20735 2024-10-02 20:45:00  15.6

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00   6.3
1   2024-10-02 00:05:00   6.4
2   2024-10-02 00:10:00   6.1
3   2024-10-02 00:15:00  18.3
4   2024-10-02 00:20:00   6.1
..                  ...   ...
283 2024-10-02 23:35:00   7.5
284 2024-10-02 23:40:00  18.1
285 2024-10-02 23:45:00   7.2
286 2024-10-02 23:50:00   7.0
287 2024-10-02 23:55:00   6.7

[288 rows x 2 columns]
shape cleaned
(288, 2)
1888

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 02:45:00  14.5
1     2024-10-02 02:40:00  14.5
2     2024-10-02 02:35:00  14.8
3     2024-10-02 02:30:00  15.1
4     2024-10-02 02:25:00  15.6
...                   ...   ...
20731 2024-10-02 21:05:00   6.1
20732 2024-10-02 21:00:00   6.0
20733 2024-10-02 20:55:00   5.9
20734 2024-10-02 20:50:00   5.9
20735 2024-10-02 20:45:00   5.9

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  17.8
1   2024-10-02 00:05:00  18.0
2   2024-10-02 00:10:00  18.1
3   2024-10-02 00:15:00   5.3
4   2024-10-02 00:20:00  18.3
..                  ...   ...
283 2024-10-02 23:35:00  18.5
284 2024-10-02 23:40:00   5.5
285 2024-10-02 23:45:00  17.8
286 2024-10-02 23:50:00  17.7
287 2024-10-02 23:55:00  17.6

[288 rows x 2 columns]
shape cleaned
(288, 2)
2176

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 02:45:00  4.1
1     2024-10-02 02:40:00  4.3
2     2024-10-02 02:35:00  4.7
3     2024-10-02 02:30:00  5.0
4     2024-10-02 02:25:00  5.2
...                   ...  ...
20731 2024-10-02 21:05:00  9.7
20732 2024-10-02 21:00:00  9.5
20733 2024-10-02 20:55:00  9.5
20734 2024-10-02 20:50:00  9.5
20735 2024-10-02 20:45:00  9.4

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00   5.5
1   2024-10-02 00:05:00   5.5
2   2024-10-02 00:10:00   5.4
3   2024-10-02 00:15:00  12.4
4   2024-10-02 00:20:00   5.2
..                  ...   ...
283 2024-10-02 23:35:00   5.7
284 2024-10-02 23:40:00  10.3
285 2024-10-02 23:45:00   5.3
286 2024-10-02 23:50:00   5.1
287 2024-10-02 23:55:00   5.3

[288 rows x 2 columns]
shape cleaned
(288, 2)
2464

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 02:45:00  12.2
1     2024-10-02 02:40:00  12.4
2     2024-10-02 02:35:00  12.7
3     2024-10-02 02:30:00  12.7
4     2024-10-02 02:25:00  12.8
...                   ...   ...
20731 2024-10-02 21:05:00   5.3
20732 2024-10-02 21:00:00   5.5
20733 2024-10-02 20:55:00   5.7
20734 2024-10-02 20:50:00   5.9
20735 2024-10-02 20:45:00   6.0

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  11.8
1   2024-10-02 00:05:00  12.2
2   2024-10-02 00:10:00  12.2
3   2024-10-02 00:15:00  11.8
4   2024-10-02 00:20:00  12.7
..                  ...   ...
283 2024-10-02 23:35:00  10.0
284 2024-10-02 23:40:00   9.3
285 2024-10-02 23:45:00  10.6
286 2024-10-02 23:50:00  11.1
287 2024-10-02 23:55:00  11.4

[288 rows x 2 columns]
shape cleaned
(288, 2)
2752

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 02:45:00  7.9
1     2024-10-02 02:40:00  7.9
2     2024-10-02 02:35:00  8.2
3     2024-10-02 02:30:00  8.5
4     2024-10-02 02:25:00  8.9
...                   ...  ...
20731 2024-10-02 21:05:00  8.4
20732 2024-10-02 21:00:00  7.8
20733 2024-10-02 20:55:00  7.2
20734 2024-10-02 20:50:00  6.0
20735 2024-10-02 20:45:00  5.0

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  10.9
1   2024-10-02 00:05:00  11.3
2   2024-10-02 00:10:00  11.5
3   2024-10-02 00:15:00   5.7
4   2024-10-02 00:20:00  12.1
..                  ...   ...
283 2024-10-02 23:35:00   8.8
284 2024-10-02 23:40:00   7.4
285 2024-10-02 23:45:00   9.6
286 2024-10-02 23:50:00   9.9
287 2024-10-02 23:55:00  10.4

[288 rows x 2 columns]
shape cleaned
(288, 2)
3040

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 02:45:00  8.4
1     2024-10-02 02:40:00  8.0
2     2024-10-02 02:35:00  7.9
3     2024-10-02 02:30:00  7.8
4     2024-10-02 02:25:00  7.8
...                   ...  ...
20731 2024-10-02 23:05:00  6.2
20732 2024-10-02 23:00:00  5.9
20733 2024-10-02 22:55:00  6.0
20734 2024-10-02 22:50:00  6.1
20735 2024-10-02 22:45:00  6.2

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  5.9
1   2024-10-02 00:05:00  5.3
2   2024-10-02 00:10:00  6.2
3   2024-10-02 00:15:00  6.3
4   2024-10-02 00:20:00  6.6
..                  ...  ...
283 2024-10-02 23:35:00  6.4
284 2024-10-02 23:40:00  6.2
285 2024-10-02 23:45:00  7.3
286 2024-10-02 23:50:00  7.0
287 2024-10-02 23:55:00  5.9

[288 rows x 2 columns]
shape cleaned
(288, 2)
3328

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 04:45:00   6.2
1     2024-10-02 04:40:00   6.3
2     2024-10-02 04:35:00   6.5
3     2024-10-02 04:30:00   6.3
4     2024-10-02 04:25:00   6.2
...                   ...   ...
20731 2024-10-02 23:05:00  10.5
20732 2024-10-02 23:00:00  10.6
20733 2024-10-02 22:55:00  10.9
20734 2024-10-02 22:50:00  11.0
20735 2024-10-02 22:45:00  11.0

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  10.8
1   2024-10-02 00:05:00  10.7
2   2024-10-02 00:10:00  10.4
3   2024-10-02 00:15:00  10.1
4   2024-10-02 00:20:00   9.8
..                  ...   ...
283 2024-10-02 23:35:00   9.6
284 2024-10-02 23:40:00   9.4
285 2024-10-02 23:45:00   9.7
286 2024-10-02 23:50:00   5.9
287 2024-10-02 23:55:00  10.4

[288 rows x 2 columns]
shape cleaned
(288, 2)
3616

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 04:45:00  7.5
1     2024-10-02 04:40:00  7.5
2     2024-10-02 04:35:00  7.7
3     2024-10-02 04:30:00  7.7
4     2024-10-02 04:25:00  7.8
...                   ...  ...
20731 2024-10-02 23:05:00  7.3
20732 2024-10-02 23:00:00  7.3
20733 2024-10-02 22:55:00  7.3
20734 2024-10-02 22:50:00  7.2
20735 2024-10-02 22:45:00  7.2

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00   7.5
1   2024-10-02 00:05:00   7.5
2   2024-10-02 00:10:00   7.5
3   2024-10-02 00:15:00   7.6
4   2024-10-02 00:20:00   7.7
..                  ...   ...
283 2024-10-02 23:35:00   7.5
284 2024-10-02 23:40:00   7.3
285 2024-10-02 23:45:00   7.3
286 2024-10-02 23:50:00  10.0
287 2024-10-02 23:55:00   7.4

[288 rows x 2 columns]
shape cleaned
(288, 2)
3904

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 04:45:00  6.8
1     2024-10-02 04:40:00  7.1
2     2024-10-02 04:35:00  7.4
3     2024-10-02 04:30:00  7.4
4     2024-10-02 04:25:00  7.5
...                   ...  ...
20731 2024-10-02 23:05:00  8.6
20732 2024-10-02 23:00:00  8.4
20733 2024-10-02 22:55:00  8.2
20734 2024-10-02 22:50:00  8.1
20735 2024-10-02 22:45:00  8.3

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  7.7
1   2024-10-02 00:05:00  7.7
2   2024-10-02 00:10:00  7.8
3   2024-10-02 00:15:00  7.9
4   2024-10-02 00:20:00  7.8
..                  ...  ...
283 2024-10-02 23:35:00  8.7
284 2024-10-02 23:40:00  8.5
285 2024-10-02 23:45:00  8.2
286 2024-10-02 23:50:00  7.3
287 2024-10-02 23:55:00  7.7

[288 rows x 2 columns]
shape cleaned
(288, 2)
4192

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 04:45:00   6.7
1     2024-10-02 04:40:00   6.5
2     2024-10-02 04:35:00   6.1
3     2024-10-02 04:30:00   5.9
4     2024-10-02 04:25:00   5.8
...                   ...   ...
20731 2024-10-02 23:05:00  12.0
20732 2024-10-02 23:00:00  12.2
20733 2024-10-02 22:55:00  12.1
20734 2024-10-02 22:50:00  12.5
20735 2024-10-02 22:45:00  12.9

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  8.5
1   2024-10-02 00:05:00  8.6
2   2024-10-02 00:10:00  8.5
3   2024-10-02 00:15:00  8.5
4   2024-10-02 00:20:00  8.4
..                  ...  ...
283 2024-10-02 23:35:00  9.5
284 2024-10-02 23:40:00  8.9
285 2024-10-02 23:45:00  8.8
286 2024-10-02 23:50:00  7.9
287 2024-10-02 23:55:00  8.7

[288 rows x 2 columns]
shape cleaned
(288, 2)
4480

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 04:45:00  6.8
1     2024-10-02 04:40:00  6.8
2     2024-10-02 04:35:00  6.8
3     2024-10-02 04:30:00  6.8
4     2024-10-02 04:25:00  6.8
...                   ...  ...
20731 2024-10-02 23:05:00  9.5
20732 2024-10-02 23:00:00  9.4
20733 2024-10-02 22:55:00  9.5
20734 2024-10-02 22:50:00  9.5
20735 2024-10-02 22:45:00  9.2

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  6.6
1   2024-10-02 00:05:00  5.8
2   2024-10-02 00:10:00  5.3
3   2024-10-02 00:15:00  5.7
4   2024-10-02 00:20:00  5.7
..                  ...  ...
283 2024-10-02 23:35:00  8.0
284 2024-10-02 23:40:00  7.7
285 2024-10-02 23:45:00  7.7
286 2024-10-02 23:50:00  8.7
287 2024-10-02 23:55:00  7.2

[288 rows x 2 columns]
shape cleaned
(288, 2)
4768

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 04:45:00   4.6
1     2024-10-02 04:40:00   4.6
2     2024-10-02 04:35:00   4.4
3     2024-10-02 04:30:00   4.4
4     2024-10-02 04:25:00   4.4
...                   ...   ...
20731 2024-10-02 23:05:00  10.7
20732 2024-10-02 23:00:00  11.1
20733 2024-10-02 22:55:00  11.5
20734 2024-10-02 22:50:00  11.9
20735 2024-10-02 22:45:00  12.1

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  10.8
1   2024-10-02 00:05:00  10.6
2   2024-10-02 00:10:00  10.4
3   2024-10-02 00:15:00  10.2
4   2024-10-02 00:20:00  10.4
..                  ...   ...
283 2024-10-02 23:35:00  10.9
284 2024-10-02 23:40:00  11.0
285 2024-10-02 23:45:00  10.9
286 2024-10-02 23:50:00   7.6
287 2024-10-02 23:55:00  10.8

[288 rows x 2 columns]
shape cleaned
(288, 2)
5056

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 04:45:00  9.3
1     2024-10-02 04:40:00  9.4
2     2024-10-02 04:35:00  9.5
3     2024-10-02 04:30:00  9.5
4     2024-10-02 04:25:00  9.5
...                   ...  ...
20731 2024-10-02 03:35:00  8.6
20732 2024-10-02 03:30:00  8.9
20733 2024-10-02 03:25:00  9.0
20734 2024-10-02 03:20:00  9.0
20735 2024-10-02 03:15:00  9.3

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00   9.1
1   2024-10-02 00:05:00   9.3
2   2024-10-02 00:10:00   9.4
3   2024-10-02 00:15:00   9.1
4   2024-10-02 00:20:00   9.1
..                  ...   ...
283 2024-10-02 23:35:00   7.5
284 2024-10-02 23:40:00  11.0
285 2024-10-02 23:45:00   7.5
286 2024-10-02 23:50:00   7.6
287 2024-10-02 23:55:00   8.3

[288 rows x 2 columns]
shape cleaned
(288, 2)
5344

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 09:15:00  5.2
1     2024-10-02 09:10:00  4.9
2     2024-10-02 09:05:00  4.7
3     2024-10-02 09:00:00  4.7
4     2024-10-02 08:55:00  4.9
...                   ...  ...
20731 2024-10-02 03:35:00  7.0
20732 2024-10-02 03:30:00  7.1
20733 2024-10-02 03:25:00  7.3
20734 2024-10-02 03:20:00  7.1
20735 2024-10-02 03:15:00  7.0

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  11.7
1   2024-10-02 00:05:00  11.7
2   2024-10-02 00:10:00  11.3
3   2024-10-02 00:15:00  10.8
4   2024-10-02 00:20:00  10.5
..                  ...   ...
283 2024-10-02 23:35:00  11.8
284 2024-10-02 23:40:00  11.5
285 2024-10-02 23:45:00  11.5
286 2024-10-02 23:50:00  11.5
287 2024-10-02 23:55:00  11.6

[288 rows x 2 columns]
shape cleaned
(288, 2)
5632

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 09:15:00  6.9
1     2024-10-02 09:10:00  6.9
2     2024-10-02 09:05:00  6.9
3     2024-10-02 09:00:00  6.9
4     2024-10-02 08:55:00  6.9
...                   ...  ...
20731 2024-10-02 03:35:00  8.2
20732 2024-10-02 03:30:00  8.3
20733 2024-10-02 03:25:00  8.5
20734 2024-10-02 03:20:00  8.7
20735 2024-10-02 03:15:00  9.0

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  11.6
1   2024-10-02 00:05:00  12.0
2   2024-10-02 00:10:00  12.1
3   2024-10-02 00:15:00  12.1
4   2024-10-02 00:20:00  12.0
..                  ...   ...
283 2024-10-02 23:35:00  11.3
284 2024-10-02 23:40:00  11.2
285 2024-10-02 23:45:00  11.0
286 2024-10-02 23:50:00  11.2
287 2024-10-02 23:55:00  11.4

[288 rows x 2 columns]
shape cleaned
(288, 2)
5920

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 09:15:00  7.2
1     2024-10-02 09:10:00  7.4
2     2024-10-02 09:05:00  7.7
3     2024-10-02 09:00:00  7.8
4     2024-10-02 08:55:00  7.9
...                   ...  ...
20731 2024-10-02 03:35:00  7.2
20732 2024-10-02 03:30:00  7.3
20733 2024-10-02 03:25:00  7.2
20734 2024-10-02 03:20:00  7.3
20735 2024-10-02 03:15:00  7.5

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  12.0
1   2024-10-02 00:05:00  12.1
2   2024-10-02 00:10:00  12.2
3   2024-10-02 00:15:00  12.2
4   2024-10-02 00:20:00  12.2
..                  ...   ...
283 2024-10-02 23:35:00  13.3
284 2024-10-02 23:40:00  13.5
285 2024-10-02 23:45:00  13.1
286 2024-10-02 23:50:00  12.8
287 2024-10-02 23:55:00  12.2

[288 rows x 2 columns]
shape cleaned
(288, 2)
6208

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 09:15:00  6.8
1     2024-10-02 09:10:00  7.0
2     2024-10-02 09:05:00  7.2
3     2024-10-02 09:00:00  7.1
4     2024-10-02 08:55:00  7.0
...                   ...  ...
20731 2024-10-02 03:35:00  6.9
20732 2024-10-02 03:30:00  7.1
20733 2024-10-02 03:25:00  7.2
20734 2024-10-02 03:20:00  7.2
20735 2024-10-02 03:15:00  7.3

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  6.2
1   2024-10-02 00:05:00  6.3
2   2024-10-02 00:10:00  6.5
3   2024-10-02 00:15:00  6.7
4   2024-10-02 00:20:00  6.8
..                  ...  ...
283 2024-10-02 23:35:00  5.9
284 2024-10-02 23:40:00  6.0
285 2024-10-02 23:45:00  6.0
286 2024-10-02 23:50:00  6.1
287 2024-10-02 23:55:00  6.2

[288 rows x 2 columns]
shape cleaned
(288, 2)
6496

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 09:15:00  6.4
1     2024-10-02 09:10:00  6.5
2     2024-10-02 09:05:00  6.5
3     2024-10-02 09:00:00  6.5
4     2024-10-02 08:55:00  6.4
...                   ...  ...
20731 2024-10-02 03:35:00  4.5
20732 2024-10-02 03:30:00  4.6
20733 2024-10-02 03:25:00  4.7
20734 2024-10-02 03:20:00  4.8
20735 2024-10-02 03:15:00  4.8

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  4.7
1   2024-10-02 00:05:00  4.7
2   2024-10-02 00:10:00  4.8
3   2024-10-02 00:15:00  4.8
4   2024-10-02 00:20:00  4.7
..                  ...  ...
283 2024-10-02 23:35:00  4.6
284 2024-10-02 23:40:00  4.3
285 2024-10-02 23:45:00  4.4
286 2024-10-02 23:50:00  4.4
287 2024-10-02 23:55:00  4.6

[288 rows x 2 columns]
shape cleaned
(288, 2)
6784

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 09:15:00   5.7
1     2024-10-02 09:10:00   5.6
2     2024-10-02 09:05:00   5.5
3     2024-10-02 09:00:00   5.5
4     2024-10-02 08:55:00   5.5
...                   ...   ...
20731 2024-10-02 03:35:00  12.6
20732 2024-10-02 03:30:00  12.5
20733 2024-10-02 03:25:00  12.4
20734 2024-10-02 03:20:00  12.1
20735 2024-10-02 03:15:00  11.8

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  7.8
1   2024-10-02 00:05:00  8.4
2   2024-10-02 00:10:00  8.8
3   2024-10-02 00:15:00  9.0
4   2024-10-02 00:20:00  9.3
..                  ...  ...
283 2024-10-02 23:35:00  6.8
284 2024-10-02 23:40:00  6.3
285 2024-10-02 23:45:00  6.3
286 2024-10-02 23:50:00  6.6
287 2024-10-02 23:55:00  7.0

[288 rows x 2 columns]
shape cleaned
(288, 2)
7072

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 09:15:00  5.2
1     2024-10-02 09:10:00  5.1
2     2024-10-02 09:05:00  5.0
3     2024-10-02 09:00:00  5.0
4     2024-10-02 08:55:00  5.2
...                   ...  ...
20731 2024-10-02 12:40:00  6.6
20732 2024-10-02 12:35:00  6.7
20733 2024-10-02 12:30:00  6.7
20734 2024-10-02 12:25:00  6.7
20735 2024-10-02 12:20:00  6.7

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00   NaN
1   2024-10-02 00:05:00   NaN
2   2024-10-02 00:10:00   NaN
3   2024-10-02 00:15:00   NaN
4   2024-10-02 00:20:00   NaN
..                  ...   ...
278 2024-10-02 23:35:00  11.8
279 2024-10-02 23:40:00  11.8
280 2024-10-02 23:45:00  11.8
281 2024-10-02 23:50:00  11.8
282 2024-10-02 23:55:00  11.8

[283 rows x 2 columns]
shape cleaned
(283, 2)
7360

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 18:20:00  12.2
1     2024-10-02 18:15:00  11.8
2     2024-10-02 18:10:00  11.2
3     2024-10-02 18:05:00  10.7
4     2024-10-02 18:00:00  10.6
...                   ...   ...
20731 2024-10-02 12:40:00   5.3
20732 2024-10-02 12:35:00   5.8
20733 2024-10-02 12:30:00   5.9
20734 2024-10-02 12:25:00   5.5
20735 2024-10-02 12:20:00   5.1

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  13.6
1   2024-10-02 00:05:00  14.0
2   2024-10-02 00:10:00  14.7
3   2024-10-02 00:15:00  14.9
4   2024-10-02 00:20:00  14.5
..                  ...   ...
283 2024-10-02 23:35:00  13.1
284 2024-10-02 23:40:00  13.0
285 2024-10-02 23:45:00  13.0
286 2024-10-02 23:50:00  13.1
287 2024-10-02 23:55:00  13.3

[288 rows x 2 columns]
shape cleaned
(288, 2)
7648

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 18:20:00  9.4
1     2024-10-02 18:15:00  9.3
2     2024-10-02 18:10:00  9.3
3     2024-10-02 18:05:00  9.3
4     2024-10-02 18:00:00  9.3
...                   ...  ...
20731 2024-10-02 12:40:00  5.6
20732 2024-10-02 12:35:00  5.7
20733 2024-10-02 12:30:00  5.7
20734 2024-10-02 12:25:00  5.6
20735 2024-10-02 12:20:00  5.5

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  8.4
1   2024-10-02 00:05:00  8.6
2   2024-10-02 00:10:00  8.9
3   2024-10-02 00:15:00  9.0
4   2024-10-02 00:20:00  9.3
..                  ...  ...
283 2024-10-02 23:35:00  7.5
284 2024-10-02 23:40:00  7.6
285 2024-10-02 23:45:00  7.8
286 2024-10-02 23:50:00  7.9
287 2024-10-02 23:55:00  8.2

[288 rows x 2 columns]
shape cleaned
(288, 2)
7936

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 18:20:00  11.0
1     2024-10-02 18:15:00  10.8
2     2024-10-02 18:10:00  10.4
3     2024-10-02 18:05:00  10.2
4     2024-10-02 18:00:00  10.0
...                   ...   ...
20731 2024-10-02 12:40:00   6.2
20732 2024-10-02 12:35:00   6.0
20733 2024-10-02 12:30:00   6.1
20734 2024-10-02 12:25:00   6.2
20735 2024-10-02 12:20:00   6.3

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  10.9
1   2024-10-02 00:05:00  10.3
2   2024-10-02 00:10:00   9.8
3   2024-10-02 00:15:00   9.8
4   2024-10-02 00:20:00   9.9
..                  ...   ...
283 2024-10-02 23:35:00  11.4
284 2024-10-02 23:40:00  11.5
285 2024-10-02 23:45:00  11.7
286 2024-10-02 23:50:00  11.7
287 2024-10-02 23:55:00  11.4

[288 rows x 2 columns]
shape cleaned
(288, 2)
8224

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 18:20:00  12.1
1     2024-10-02 18:15:00  12.3
2     2024-10-02 18:10:00  12.7
3     2024-10-02 18:05:00  13.3
4     2024-10-02 18:00:00  14.0
...                   ...   ...
20731 2024-10-02 12:40:00   6.7
20732 2024-10-02 12:35:00   6.7
20733 2024-10-02 12:30:00   6.7
20734 2024-10-02 12:25:00   6.5
20735 2024-10-02 12:20:00   6.5

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  8.8
1   2024-10-02 00:05:00  8.8
2   2024-10-02 00:10:00  8.8
3   2024-10-02 00:15:00  8.8
4   2024-10-02 00:20:00  8.8
..                  ...  ...
283 2024-10-02 23:35:00  8.2
284 2024-10-02 23:40:00  8.5
285 2024-10-02 23:45:00  8.7
286 2024-10-02 23:50:00  8.8
287 2024-10-02 23:55:00  8.8

[288 rows x 2 columns]
shape cleaned
(288, 2)
8512

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 18:20:00  7.5
1     2024-10-02 18:15:00  7.5
2     2024-10-02 18:10:00  7.7
3     2024-10-02 18:05:00  7.7
4     2024-10-02 18:00:00  7.6
...                   ...  ...
20731 2024-10-02 12:40:00  5.8
20732 2024-10-02 12:35:00  5.5
20733 2024-10-02 12:30:00  5.2
20734 2024-10-02 12:25:00  4.9
20735 2024-10-02 12:20:00  4.7

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  5.0
1   2024-10-02 00:05:00  5.2
2   2024-10-02 00:10:00  5.4
3   2024-10-02 00:15:00  5.7
4   2024-10-02 00:20:00  5.8
..                  ...  ...
283 2024-10-02 23:35:00  5.0
284 2024-10-02 23:40:00  4.9
285 2024-10-02 23:45:00  4.9
286 2024-10-02 23:50:00  4.8
287 2024-10-02 23:55:00  4.9

[288 rows x 2 columns]
shape cleaned
(288, 2)
8800

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 18:20:00  6.1
1     2024-10-02 18:15:00  6.7
2     2024-10-02 18:10:00  7.1
3     2024-10-02 18:05:00  7.4
4     2024-10-02 18:00:00  7.7
...                   ...  ...
20731 2024-10-02 12:40:00  6.2
20732 2024-10-02 12:35:00  6.1
20733 2024-10-02 12:30:00  5.9
20734 2024-10-02 12:25:00  5.8
20735 2024-10-02 12:20:00  5.8

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  5.2
1   2024-10-02 00:05:00  4.9
2   2024-10-02 00:10:00  4.9
3   2024-10-02 00:15:00  4.9
4   2024-10-02 00:20:00  5.1
..                  ...  ...
283 2024-10-02 23:35:00  6.0
284 2024-10-02 23:40:00  5.9
285 2024-10-02 23:45:00  5.8
286 2024-10-02 23:50:00  5.7
287 2024-10-02 23:55:00  5.4

[288 rows x 2 columns]
shape cleaned
(288, 2)
9088

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 18:20:00  5.8
1     2024-10-02 18:15:00  5.7
2     2024-10-02 18:10:00  5.6
3     2024-10-02 18:05:00  5.5
4     2024-10-02 18:00:00  5.5
...                   ...  ...
20731 2024-10-02 14:40:00  8.0
20732 2024-10-02 14:35:00  7.9
20733 2024-10-02 14:30:00  7.9
20734 2024-10-02 14:25:00  7.7
20735 2024-10-02 14:20:00  7.5

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  11.8
1   2024-10-02 00:05:00  12.1
2   2024-10-02 00:10:00  11.7
3   2024-10-02 00:15:00  11.7
4   2024-10-02 00:20:00  11.7
..                  ...   ...
283 2024-10-02 23:35:00   8.4
284 2024-10-02 23:40:00   9.4
285 2024-10-02 23:45:00  10.3
286 2024-10-02 23:50:00  11.0
287 2024-10-02 23:55:00  11.4

[288 rows x 2 columns]
shape cleaned
(288, 2)
9376

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 20:20:00  20.4
1     2024-10-02 20:15:00  20.4
2     2024-10-02 20:10:00  20.4
3     2024-10-02 20:05:00  20.5
4     2024-10-02 20:00:00  20.3
...                   ...   ...
20731 2024-10-02 14:40:00   4.2
20732 2024-10-02 14:35:00   4.3
20733 2024-10-02 14:30:00   4.3
20734 2024-10-02 14:25:00   4.3
20735 2024-10-02 14:20:00   4.3

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  10.7
1   2024-10-02 00:05:00  10.0
2   2024-10-02 00:10:00   9.6
3   2024-10-02 00:15:00   9.9
4   2024-10-02 00:20:00  10.0
..                  ...   ...
283 2024-10-02 23:35:00  13.0
284 2024-10-02 23:40:00  12.2
285 2024-10-02 23:45:00  11.4
286 2024-10-02 23:50:00  11.0
287 2024-10-02 23:55:00  10.6

[288 rows x 2 columns]
shape cleaned
(288, 2)
9664

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 20:20:00  14.9
1     2024-10-02 20:15:00  14.7
2     2024-10-02 20:10:00  14.1
3     2024-10-02 20:05:00  13.9
4     2024-10-02 20:00:00  13.8
...                   ...   ...
20731 2024-10-02 14:40:00   6.7
20732 2024-10-02 14:35:00   6.2
20733 2024-10-02 14:30:00   5.7
20734 2024-10-02 14:25:00   5.3
20735 2024-10-02 14:20:00   4.9

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  7.7
1   2024-10-02 00:05:00  7.7
2   2024-10-02 00:10:00  7.5
3   2024-10-02 00:15:00  7.5
4   2024-10-02 00:20:00  7.5
..                  ...  ...
283 2024-10-02 23:35:00  7.4
284 2024-10-02 23:40:00  7.8
285 2024-10-02 23:45:00  7.9
286 2024-10-02 23:50:00  8.0
287 2024-10-02 23:55:00  7.9

[288 rows x 2 columns]
shape cleaned
(288, 2)
9952

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 20:20:00  9.8
1     2024-10-02 20:15:00  9.0
2     2024-10-02 20:10:00  8.0
3     2024-10-02 20:05:00  7.7
4     2024-10-02 20:00:00  7.4
...                   ...  ...
20731 2024-10-02 14:40:00  6.6
20732 2024-10-02 14:35:00  6.6
20733 2024-10-02 14:30:00  6.6
20734 2024-10-02 14:25:00  6.6
20735 2024-10-02 14:20:00  6.7

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00   9.4
1   2024-10-02 00:05:00  10.2
2   2024-10-02 00:10:00  10.7
3   2024-10-02 00:15:00  11.2
4   2024-10-02 00:20:00  11.7
..                  ...   ...
283 2024-10-02 23:35:00   7.2
284 2024-10-02 23:40:00   7.1
285 2024-10-02 23:45:00   7.5
286 2024-10-02 23:50:00   7.9
287 2024-10-02 23:55:00   8.5

[288 rows x 2 columns]
shape cleaned
(288, 2)
10240

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 20:20:00  8.1
1     2024-10-02 20:15:00  7.9
2     2024-10-02 20:10:00  8.1
3     2024-10-02 20:05:00  8.1
4     2024-10-02 20:00:00  8.2
...                   ...  ...
20731 2024-10-02 14:40:00  8.4
20732 2024-10-02 14:35:00  8.1
20733 2024-10-02 14:30:00  7.8
20734 2024-10-02 14:25:00  6.9
20735 2024-10-02 14:20:00  6.4

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  7.9
1   2024-10-02 00:05:00  7.7
2   2024-10-02 00:10:00  7.7
3   2024-10-02 00:15:00  7.8
4   2024-10-02 00:20:00  7.7
..                  ...  ...
283 2024-10-02 23:35:00  9.2
284 2024-10-02 23:40:00  9.0
285 2024-10-02 23:45:00  8.8
286 2024-10-02 23:50:00  8.4
287 2024-10-02 23:55:00  8.2

[288 rows x 2 columns]
shape cleaned
(288, 2)
10528

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 20:20:00  5.5
1     2024-10-02 20:15:00  5.6
2     2024-10-02 20:10:00  5.7
3     2024-10-02 20:05:00  5.6
4     2024-10-02 20:00:00  5.5
...                   ...  ...
20731 2024-10-02 14:40:00  5.4
20732 2024-10-02 14:35:00  5.4
20733 2024-10-02 14:30:00  5.3
20734 2024-10-02 14:25:00  5.3
20735 2024-10-02 14:20:00  5.3

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  7.3
1   2024-10-02 00:05:00  8.0
2   2024-10-02 00:10:00  8.7
3   2024-10-02 00:15:00  9.3
4   2024-10-02 00:20:00  9.8
..                  ...  ...
283 2024-10-02 23:35:00  5.5
284 2024-10-02 23:40:00  5.6
285 2024-10-02 23:45:00  5.7
286 2024-10-02 23:50:00  6.0
287 2024-10-02 23:55:00  6.4

[288 rows x 2 columns]
shape cleaned
(288, 2)
10816

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 20:20:00  5.0
1     2024-10-02 20:15:00  5.3
2     2024-10-02 20:10:00  5.3
3     2024-10-02 20:05:00  5.9
4     2024-10-02 20:00:00  6.2
...                   ...  ...
20731 2024-10-02 14:40:00  5.9
20732 2024-10-02 14:35:00  6.0
20733 2024-10-02 14:30:00  6.0
20734 2024-10-02 14:25:00  6.0
20735 2024-10-02 14:20:00  6.2

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  4.9
1   2024-10-02 00:05:00  4.6
2   2024-10-02 00:10:00  4.8
3   2024-10-02 00:15:00  5.2
4   2024-10-02 00:20:00  5.9
..                  ...  ...
283 2024-10-02 23:35:00  7.0
284 2024-10-02 23:40:00  6.5
285 2024-10-02 23:45:00  6.0
286 2024-10-02 23:50:00  5.7
287 2024-10-02 23:55:00  5.3

[288 rows x 2 columns]
shape cleaned
(288, 2)
11104

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 20:20:00  4.4
1     2024-10-02 20:15:00  4.6
2     2024-10-02 20:10:00  4.8
3     2024-10-02 20:05:00  4.9
4     2024-10-02 20:00:00  5.0
...                   ...  ...
20731 2024-10-02 03:55:00  7.1
20732 2024-10-02 03:50:00  7.0
20733 2024-10-02 03:45:00  7.2
20734 2024-10-02 03:40:00  7.5
20735 2024-10-02 03:35:00  7.7

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  8.3
1   2024-10-02 00:05:00  8.4
2   2024-10-02 00:10:00  8.5
3   2024-10-02 00:15:00  8.7
4   2024-10-02 00:20:00  8.8
..                  ...  ...
283 2024-10-02 23:35:00  8.4
284 2024-10-02 23:40:00  8.3
285 2024-10-02 23:45:00  8.2
286 2024-10-02 23:50:00  8.2
287 2024-10-02 23:55:00  8.2

[288 rows x 2 columns]
shape cleaned
(288, 2)
11392

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 09:35:00  6.8
1     2024-10-02 09:30:00  6.8
2     2024-10-02 09:25:00  6.8
3     2024-10-02 09:20:00  6.9
4     2024-10-02 09:15:00  6.9
...                   ...  ...
20731 2024-10-02 03:55:00  5.2
20732 2024-10-02 03:50:00  4.9
20733 2024-10-02 03:45:00  4.8
20734 2024-10-02 03:40:00  4.7
20735 2024-10-02 03:35:00  4.6

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  4.9
1   2024-10-02 00:05:00  5.2
2   2024-10-02 00:10:00  5.7
3   2024-10-02 00:15:00  6.3
4   2024-10-02 00:20:00  6.9
..                  ...  ...
283 2024-10-02 23:35:00  5.2
284 2024-10-02 23:40:00  4.8
285 2024-10-02 23:45:00  4.7
286 2024-10-02 23:50:00  4.8
287 2024-10-02 23:55:00  4.8

[288 rows x 2 columns]
shape cleaned
(288, 2)
11680

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 09:35:00  7.0
1     2024-10-02 09:30:00  7.0
2     2024-10-02 09:25:00  7.0
3     2024-10-02 09:20:00  6.9
4     2024-10-02 09:15:00  6.8
...                   ...  ...
20731 2024-10-02 03:55:00  8.3
20732 2024-10-02 03:50:00  8.4
20733 2024-10-02 03:45:00  8.4
20734 2024-10-02 03:40:00  8.3
20735 2024-10-02 03:35:00  8.2

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  11.3
1   2024-10-02 00:05:00  10.7
2   2024-10-02 00:10:00  10.5
3   2024-10-02 00:15:00   9.9
4   2024-10-02 00:20:00   9.3
..                  ...   ...
283 2024-10-02 23:35:00  11.1
284 2024-10-02 23:40:00  11.3
285 2024-10-02 23:45:00  11.5
286 2024-10-02 23:50:00  11.5
287 2024-10-02 23:55:00  11.5

[288 rows x 2 columns]
shape cleaned
(288, 2)
11968

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 09:35:00   6.5
1     2024-10-02 09:30:00   6.5
2     2024-10-02 09:25:00   6.4
3     2024-10-02 09:20:00   6.4
4     2024-10-02 09:15:00   6.5
...                   ...   ...
20731 2024-10-02 03:55:00  11.9
20732 2024-10-02 03:50:00  12.2
20733 2024-10-02 03:45:00  12.3
20734 2024-10-02 03:40:00  12.5
20735 2024-10-02 03:35:00  12.5

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  18.0
1   2024-10-02 00:05:00  18.4
2   2024-10-02 00:10:00  17.7
3   2024-10-02 00:15:00  17.3
4   2024-10-02 00:20:00  16.8
..                  ...   ...
283 2024-10-02 23:35:00  18.5
284 2024-10-02 23:40:00  18.3
285 2024-10-02 23:45:00  18.4
286 2024-10-02 23:50:00  18.6
287 2024-10-02 23:55:00  18.5

[288 rows x 2 columns]
shape cleaned
(288, 2)
12256

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 09:35:00  6.6
1     2024-10-02 09:30:00  6.6
2     2024-10-02 09:25:00  6.5
3     2024-10-02 09:20:00  6.3
4     2024-10-02 09:15:00  6.4
...                   ...  ...
20731 2024-10-02 03:55:00  8.8
20732 2024-10-02 03:50:00  8.8
20733 2024-10-02 03:45:00  8.8
20734 2024-10-02 03:40:00  8.7
20735 2024-10-02 03:35:00  8.8

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  7.7
1   2024-10-02 00:05:00  7.6
2   2024-10-02 00:10:00  7.3
3   2024-10-02 00:15:00  6.3
4   2024-10-02 00:20:00  5.6
..                  ...  ...
283 2024-10-02 23:35:00  7.2
284 2024-10-02 23:40:00  7.2
285 2024-10-02 23:45:00  7.2
286 2024-10-02 23:50:00  7.3
287 2024-10-02 23:55:00  7.4

[288 rows x 2 columns]
shape cleaned
(288, 2)
12544

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 09:35:00  7.8
1     2024-10-02 09:30:00  7.9
2     2024-10-02 09:25:00  7.8
3     2024-10-02 09:20:00  7.8
4     2024-10-02 09:15:00  7.7
...                   ...  ...
20731 2024-10-02 03:55:00  8.3
20732 2024-10-02 03:50:00  7.9
20733 2024-10-02 03:45:00  7.6
20734 2024-10-02 03:40:00  7.2
20735 2024-10-02 03:35:00  6.8

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  15.1
1   2024-10-02 00:05:00  15.1
2   2024-10-02 00:10:00  15.3
3   2024-10-02 00:15:00  15.3
4   2024-10-02 00:20:00  15.1
..                  ...   ...
283 2024-10-02 23:35:00  14.3
284 2024-10-02 23:40:00  14.4
285 2024-10-02 23:45:00  14.5
286 2024-10-02 23:50:00  14.9
287 2024-10-02 23:55:00  15.0

[288 rows x 2 columns]
shape cleaned
(288, 2)
12832

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 09:35:00  7.3
1     2024-10-02 09:30:00  7.3
2     2024-10-02 09:25:00  7.3
3     2024-10-02 09:20:00  7.3
4     2024-10-02 09:15:00  7.2
...                   ...  ...
20731 2024-10-02 14:05:00  9.4
20732 2024-10-02 14:00:00  9.3
20733 2024-10-02 13:55:00  8.9
20734 2024-10-02 13:50:00  8.7
20735 2024-10-02 13:45:00  8.5

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  11.0
1   2024-10-02 00:05:00  10.6
2   2024-10-02 00:10:00  10.7
3   2024-10-02 00:15:00  10.9
4   2024-10-02 00:20:00  10.9
..                  ...   ...
265 2024-10-02 23:35:00  12.5
266 2024-10-02 23:40:00  12.0
267 2024-10-02 23:45:00  11.7
268 2024-10-02 23:50:00  11.4
269 2024-10-02 23:55:00  11.1

[270 rows x 2 columns]
shape cleaned
(270, 2)
13120

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 19:45:00  9.5
1     2024-10-02 19:40:00  9.6
2     2024-10-02 19:35:00  9.7
3     2024-10-02 19:30:00  9.7
4     2024-10-02 19:25:00  9.5
...                   ...  ...
20731 2024-10-02 14:05:00  6.9
20732 2024-10-02 14:00:00  7.0
20733 2024-10-02 13:55:00  7.2
20734 2024-10-02 13:50:00  7.2
20735 2024-10-02 13:45:00  7.2

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00   9.0
1   2024-10-02 00:05:00   8.8
2   2024-10-02 00:10:00   9.1
3   2024-10-02 00:15:00   9.6
4   2024-10-02 00:20:00   9.7
..                  ...   ...
283 2024-10-02 23:35:00  10.0
284 2024-10-02 23:40:00   9.4
285 2024-10-02 23:45:00   8.8
286 2024-10-02 23:50:00   9.0
287 2024-10-02 23:55:00   9.2

[288 rows x 2 columns]
shape cleaned
(288, 2)
13408

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 19:45:00  6.5
1     2024-10-02 19:40:00  6.6
2     2024-10-02 19:35:00  6.7
3     2024-10-02 19:30:00  6.7
4     2024-10-02 19:25:00  6.8
...                   ...  ...
20731 2024-10-02 14:05:00  6.2
20732 2024-10-02 14:00:00  6.1
20733 2024-10-02 13:55:00  6.1
20734 2024-10-02 13:50:00  6.2
20735 2024-10-02 13:45:00  6.3

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  7.9
1   2024-10-02 00:05:00  7.9
2   2024-10-02 00:10:00  8.0
3   2024-10-02 00:15:00  8.2
4   2024-10-02 00:20:00  8.2
..                  ...  ...
283 2024-10-02 23:35:00  6.5
284 2024-10-02 23:40:00  6.7
285 2024-10-02 23:45:00  6.9
286 2024-10-02 23:50:00  7.2
287 2024-10-02 23:55:00  7.8

[288 rows x 2 columns]
shape cleaned
(288, 2)
13696

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 19:45:00  9.0
1     2024-10-02 19:40:00  9.1
2     2024-10-02 19:35:00  9.2
3     2024-10-02 19:30:00  9.2
4     2024-10-02 19:25:00  9.3
...                   ...  ...
20731 2024-10-02 14:05:00  8.4
20732 2024-10-02 14:00:00  8.4
20733 2024-10-02 13:55:00  8.4
20734 2024-10-02 13:50:00  8.0
20735 2024-10-02 13:45:00  7.5

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  7.6
1   2024-10-02 00:05:00  7.6
2   2024-10-02 00:10:00  7.6
3   2024-10-02 00:15:00  7.5
4   2024-10-02 00:20:00  7.3
..                  ...  ...
283 2024-10-02 23:35:00  7.0
284 2024-10-02 23:40:00  7.1
285 2024-10-02 23:45:00  7.2
286 2024-10-02 23:50:00  7.4
287 2024-10-02 23:55:00  7.5

[288 rows x 2 columns]
shape cleaned
(288, 2)
13984

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 19:45:00  9.8
1     2024-10-02 19:40:00  9.2
2     2024-10-02 19:35:00  8.7
3     2024-10-02 19:30:00  8.2
4     2024-10-02 19:25:00  8.0
...                   ...  ...
20731 2024-10-02 14:05:00  6.7
20732 2024-10-02 14:00:00  6.7
20733 2024-10-02 13:55:00  6.7
20734 2024-10-02 13:50:00  6.6
20735 2024-10-02 13:45:00  6.7

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  5.4
1   2024-10-02 00:05:00  5.5
2   2024-10-02 00:10:00  5.4
3   2024-10-02 00:15:00  5.2
4   2024-10-02 00:20:00  5.2
..                  ...  ...
283 2024-10-02 23:35:00  6.9
284 2024-10-02 23:40:00  6.2
285 2024-10-02 23:45:00  5.9
286 2024-10-02 23:50:00  5.5
287 2024-10-02 23:55:00  5.4

[288 rows x 2 columns]
shape cleaned
(288, 2)
14272

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 19:45:00  6.4
1     2024-10-02 19:40:00  6.6
2     2024-10-02 19:35:00  6.7
3     2024-10-02 19:30:00  6.8
4     2024-10-02 19:25:00  6.8
...                   ...  ...
20731 2024-10-02 14:05:00  6.9
20732 2024-10-02 14:00:00  6.8
20733 2024-10-02 13:55:00  6.7
20734 2024-10-02 13:50:00  6.5
20735 2024-10-02 13:45:00  6.4

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  6.4
1   2024-10-02 00:05:00  6.6
2   2024-10-02 00:10:00  6.8
3   2024-10-02 00:15:00  7.0
4   2024-10-02 00:20:00  7.2
..                  ...  ...
283 2024-10-02 23:35:00  7.2
284 2024-10-02 23:40:00  6.9
285 2024-10-02 23:45:00  6.7
286 2024-10-02 23:50:00  6.4
287 2024-10-02 23:55:00  6.3

[288 rows x 2 columns]
shape cleaned
(288, 2)
14560

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 19:45:00   4.8
1     2024-10-02 19:40:00   4.8
2     2024-10-02 19:35:00   5.0
3     2024-10-02 19:30:00   5.1
4     2024-10-02 19:25:00   5.1
...                   ...   ...
20731 2024-10-02 14:05:00  11.0
20732 2024-10-02 14:00:00  11.9
20733 2024-10-02 13:55:00  12.2
20734 2024-10-02 13:50:00  12.2
20735 2024-10-02 13:45:00  12.2

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  11.9
1   2024-10-02 00:05:00  12.4
2   2024-10-02 00:10:00  12.8
3   2024-10-02 00:15:00  12.9
4   2024-10-02 00:20:00  12.7
..                  ...   ...
283 2024-10-02 23:35:00   8.3
284 2024-10-02 23:40:00   9.2
285 2024-10-02 23:45:00  10.0
286 2024-10-02 23:50:00  10.4
287 2024-10-02 23:55:00  11.1

[288 rows x 2 columns]
shape cleaned
(288, 2)
14848

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 19:45:00  8.2
1     2024-10-02 19:40:00  8.0
2     2024-10-02 19:35:00  7.7
3     2024-10-02 19:30:00  7.3
4     2024-10-02 19:25:00  6.7
...                   ...  ...
20731 2024-10-02 16:05:00  9.9
20732 2024-10-02 16:00:00  9.6
20733 2024-10-02 15:55:00  9.5
20734 2024-10-02 15:50:00  9.3
20735 2024-10-02 15:45:00  9.7

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  6.9
1   2024-10-02 00:05:00  7.3
2   2024-10-02 00:10:00  7.8
3   2024-10-02 00:15:00  8.2
4   2024-10-02 00:20:00  8.5
..                  ...  ...
283 2024-10-02 23:35:00  5.2
284 2024-10-02 23:40:00  5.4
285 2024-10-02 23:45:00  5.5
286 2024-10-02 23:50:00  6.2
287 2024-10-02 23:55:00  6.5

[288 rows x 2 columns]
shape cleaned
(288, 2)
15136

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 21:45:00  18.0
1     2024-10-02 21:40:00  18.3
2     2024-10-02 21:35:00  18.5
3     2024-10-02 21:30:00  18.6
4     2024-10-02 21:25:00  18.9
...                   ...   ...
20731 2024-10-02 16:05:00   5.9
20732 2024-10-02 16:00:00   6.0
20733 2024-10-02 15:55:00   6.0
20734 2024-10-02 15:50:00   6.0
20735 2024-10-02 15:45:00   6.1

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  14.7
1   2024-10-02 00:05:00  13.5
2   2024-10-02 00:10:00  13.3
3   2024-10-02 00:15:00  13.2
4   2024-10-02 00:20:00  13.2
..                  ...   ...
283 2024-10-02 23:35:00  17.3
284 2024-10-02 23:40:00  16.9
285 2024-10-02 23:45:00  16.4
286 2024-10-02 23:50:00  16.0
287 2024-10-02 23:55:00  15.3

[288 rows x 2 columns]
shape cleaned
(288, 2)
15424

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 21:45:00  12.6
1     2024-10-02 21:40:00  12.5
2     2024-10-02 21:35:00  12.8
3     2024-10-02 21:30:00  12.9
4     2024-10-02 21:25:00  12.9
...                   ...   ...
20731 2024-10-02 16:05:00   5.4
20732 2024-10-02 16:00:00   4.7
20733 2024-10-02 15:55:00   3.8
20734 2024-10-02 15:50:00   3.6
20735 2024-10-02 15:45:00   3.5

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  14.5
1   2024-10-02 00:05:00  14.5
2   2024-10-02 00:10:00  14.3
3   2024-10-02 00:15:00  13.0
4   2024-10-02 00:20:00  11.9
..                  ...   ...
283 2024-10-02 23:35:00  15.1
284 2024-10-02 23:40:00  14.5
285 2024-10-02 23:45:00  14.3
286 2024-10-02 23:50:00  14.4
287 2024-10-02 23:55:00  14.4

[288 rows x 2 columns]
shape cleaned
(288, 2)
15712

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 21:45:00  22.2
1     2024-10-02 21:40:00  22.2
2     2024-10-02 21:35:00  22.2
3     2024-10-02 21:30:00  22.2
4     2024-10-02 21:25:00  22.2
...                   ...   ...
20731 2024-10-02 16:05:00   7.7
20732 2024-10-02 16:00:00   7.9
20733 2024-10-02 15:55:00   8.0
20734 2024-10-02 15:50:00   8.3
20735 2024-10-02 15:45:00   8.5

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  17.3
1   2024-10-02 00:05:00  17.6
2   2024-10-02 00:10:00  18.2
3   2024-10-02 00:15:00  18.9
4   2024-10-02 00:20:00  19.2
..                  ...   ...
283 2024-10-02 23:35:00  18.1
284 2024-10-02 23:40:00  17.4
285 2024-10-02 23:45:00  17.4
286 2024-10-02 23:50:00  16.6
287 2024-10-02 23:55:00  17.0

[288 rows x 2 columns]
shape cleaned
(288, 2)
16000

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 21:45:00  13.4
1     2024-10-02 21:40:00  13.9
2     2024-10-02 21:35:00  13.3
3     2024-10-02 21:30:00  13.4
4     2024-10-02 21:25:00  12.6
...                   ...   ...
20731 2024-10-02 05:25:00   4.9
20732 2024-10-02 05:20:00   4.8
20733 2024-10-02 05:15:00   4.9
20734 2024-10-02 05:10:00   5.0
20735 2024-10-02 05:05:00   5.0

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  5.4
1   2024-10-02 00:05:00  5.8
2   2024-10-02 00:10:00  5.7
3   2024-10-02 00:15:00  5.4
4   2024-10-02 00:20:00  5.2
..                  ...  ...
283 2024-10-02 23:35:00  3.3
284 2024-10-02 23:40:00  3.3
285 2024-10-02 23:45:00  9.9
286 2024-10-02 23:50:00  3.9
287 2024-10-02 23:55:00  4.7

[288 rows x 2 columns]
shape cleaned
(288, 2)
16288

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 11:05:00  6.4
1     2024-10-02 11:00:00  6.5
2     2024-10-02 10:55:00  6.3
3     2024-10-02 10:50:00  6.3
4     2024-10-02 10:45:00  6.2
...                   ...  ...
20731 2024-10-02 05:25:00  9.2
20732 2024-10-02 05:20:00  9.2
20733 2024-10-02 05:15:00  9.2
20734 2024-10-02 05:10:00  9.2
20735 2024-10-02 05:05:00  9.3

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  11.0
1   2024-10-02 00:05:00  10.7
2   2024-10-02 00:10:00  10.8
3   2024-10-02 00:15:00  10.9
4   2024-10-02 00:20:00  10.8
..                  ...   ...
283 2024-10-02 23:35:00   9.0
284 2024-10-02 23:40:00   9.4
285 2024-10-02 23:45:00  10.0
286 2024-10-02 23:50:00  10.3
287 2024-10-02 23:55:00  10.7

[288 rows x 2 columns]
shape cleaned
(288, 2)
16576

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 11:05:00  6.5
1     2024-10-02 11:00:00  6.3
2     2024-10-02 10:55:00  5.9
3     2024-10-02 10:50:00  5.6
4     2024-10-02 10:45:00  5.7
...                   ...  ...
20731 2024-10-02 05:25:00  8.7
20732 2024-10-02 05:20:00  8.7
20733 2024-10-02 05:15:00  8.7
20734 2024-10-02 05:10:00  8.6
20735 2024-10-02 05:05:00  8.6

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  10.6
1   2024-10-02 00:05:00  10.8
2   2024-10-02 00:10:00  11.3
3   2024-10-02 00:15:00  12.0
4   2024-10-02 00:20:00  12.0
..                  ...   ...
283 2024-10-02 23:35:00   7.7
284 2024-10-02 23:40:00   8.4
285 2024-10-02 23:45:00   9.2
286 2024-10-02 23:50:00   9.7
287 2024-10-02 23:55:00  10.2

[288 rows x 2 columns]
shape cleaned
(288, 2)
16864

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 11:05:00  7.9
1     2024-10-02 11:00:00  7.8
2     2024-10-02 10:55:00  7.5
3     2024-10-02 10:50:00  6.9
4     2024-10-02 10:45:00  6.7
...                   ...  ...
20731 2024-10-02 05:25:00  6.3
20732 2024-10-02 05:20:00  6.4
20733 2024-10-02 05:15:00  6.4
20734 2024-10-02 05:10:00  6.4
20735 2024-10-02 05:05:00  6.2

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  10.9
1   2024-10-02 00:05:00  10.7
2   2024-10-02 00:10:00  10.4
3   2024-10-02 00:15:00   9.8
4   2024-10-02 00:20:00   9.4
..                  ...   ...
283 2024-10-02 23:35:00  13.0
284 2024-10-02 23:40:00  12.8
285 2024-10-02 23:45:00  12.0
286 2024-10-02 23:50:00  11.5
287 2024-10-02 23:55:00  11.1

[288 rows x 2 columns]
shape cleaned
(288, 2)
17152

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 11:05:00  7.5
1     2024-10-02 11:00:00  7.4
2     2024-10-02 10:55:00  7.2
3     2024-10-02 10:50:00  7.2
4     2024-10-02 10:45:00  7.1
...                   ...  ...
20731 2024-10-02 09:00:00  5.4
20732 2024-10-02 08:55:00  5.4
20733 2024-10-02 08:50:00  5.5
20734 2024-10-02 08:45:00  5.4
20735 2024-10-02 08:40:00  5.5

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  12.6
1   2024-10-02 00:05:00  12.6
2   2024-10-02 00:10:00  12.7
3   2024-10-02 00:15:00  12.5
4   2024-10-02 00:20:00  12.4
..                  ...   ...
283 2024-10-02 23:35:00  13.5
284 2024-10-02 23:40:00  13.3
285 2024-10-02 23:45:00  12.9
286 2024-10-02 23:50:00  12.7
287 2024-10-02 23:55:00  12.7

[288 rows x 2 columns]
shape cleaned
(288, 2)
17440

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:121: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 14:40:00  NaN
1     2024-10-02 14:35:00  4.9
2     2024-10-02 14:30:00  5.3
3     2024-10-02 14:25:00  6.1
4     2024-10-02 14:20:00  6.2
...                   ...  ...
20731 2024-10-02 09:00:00  9.2
20732 2024-10-02 08:55:00  9.2
20733 2024-10-02 08:50:00  9.3
20734 2024-10-02 08:45:00  9.4
20735 2024-10-02 08:40:00  9.5

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00   9.7
1   2024-10-02 00:05:00   9.4
2   2024-10-02 00:10:00   9.3
3   2024-10-02 00:15:00   9.2
4   2024-10-02 00:20:00   9.3
..                  ...   ...
283 2024-10-02 23:35:00  12.7
284 2024-10-02 23:40:00  12.2
285 2024-10-02 23:45:00  11.4
286 2024-10-02 23:50:00  10.6
287 2024-10-02 23:55:00   9.9

[288 rows x 2 columns]
shape cleaned
(288, 2)
17728

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 14:40:00  12.0
1     2024-10-02 14:35:00  12.3
2     2024-10-02 14:30:00  12.4
3     2024-10-02 14:25:00  12.4
4     2024-10-02 14:20:00  12.1
...                   ...   ...
20731 2024-10-02 09:00:00   6.3
20732 2024-10-02 08:55:00   6.6
20733 2024-10-02 08:50:00   6.8
20734 2024-10-02 08:45:00   7.0
20735 2024-10-02 08:40:00   6.9

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  12.2
1   2024-10-02 00:05:00  12.4
2   2024-10-02 00:10:00  12.5
3   2024-10-02 00:15:00  12.7
4   2024-10-02 00:20:00  12.9
..                  ...   ...
283 2024-10-02 23:35:00  13.4
284 2024-10-02 23:40:00  13.0
285 2024-10-02 23:45:00  11.8
286 2024-10-02 23:50:00  11.7
287 2024-10-02 23:55:00  11.8

[288 rows x 2 columns]
shape cleaned
(288, 2)
18016

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 14:40:00  8.3
1     2024-10-02 14:35:00  7.9
2     2024-10-02 14:30:00  7.6
3     2024-10-02 14:25:00  7.5
4     2024-10-02 14:20:00  7.6
...                   ...  ...
20731 2024-10-02 09:00:00  6.3
20732 2024-10-02 08:55:00  6.5
20733 2024-10-02 08:50:00  6.4
20734 2024-10-02 08:45:00  6.8
20735 2024-10-02 08:40:00  6.8

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  9.8
1   2024-10-02 00:05:00  9.8
2   2024-10-02 00:10:00  9.9
3   2024-10-02 00:15:00  9.8
4   2024-10-02 00:20:00  9.7
..                  ...  ...
283 2024-10-02 23:35:00  9.2
284 2024-10-02 23:40:00  9.7
285 2024-10-02 23:45:00  9.8
286 2024-10-02 23:50:00  9.5
287 2024-10-02 23:55:00  9.4

[288 rows x 2 columns]
shape cleaned
(288, 2)
18304

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 14:40:00  6.8
1     2024-10-02 14:35:00  6.2
2     2024-10-02 14:30:00  5.9
3     2024-10-02 14:25:00  6.1
4     2024-10-02 14:20:00  6.0
...                   ...  ...
20731 2024-10-02 09:00:00  6.8
20732 2024-10-02 08:55:00  6.4
20733 2024-10-02 08:50:00  6.3
20734 2024-10-02 08:45:00  6.2
20735 2024-10-02 08:40:00  6.2

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  13.4
1   2024-10-02 00:05:00  12.1
2   2024-10-02 00:10:00  11.7
3   2024-10-02 00:15:00  11.4
4   2024-10-02 00:20:00  11.8
..                  ...   ...
283 2024-10-02 23:35:00  14.3
284 2024-10-02 23:40:00  14.4
285 2024-10-02 23:45:00  14.0
286 2024-10-02 23:50:00  13.8
287 2024-10-02 23:55:00  13.9

[288 rows x 2 columns]
shape cleaned
(288, 2)
18592

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 14:40:00  6.8
1     2024-10-02 14:35:00  6.7
2     2024-10-02 14:30:00  6.9
3     2024-10-02 14:25:00  6.8
4     2024-10-02 14:20:00  7.0
...                   ...  ...
20731 2024-10-02 09:00:00  6.4
20732 2024-10-02 08:55:00  6.4
20733 2024-10-02 08:50:00  6.5
20734 2024-10-02 08:45:00  6.6
20735 2024-10-02 08:40:00  6.7

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00   8.4
1   2024-10-02 00:05:00   8.4
2   2024-10-02 00:10:00   8.8
3   2024-10-02 00:15:00   9.5
4   2024-10-02 00:20:00  10.5
..                  ...   ...
283 2024-10-02 23:35:00   7.0
284 2024-10-02 23:40:00   7.9
285 2024-10-02 23:45:00   8.4
286 2024-10-02 23:50:00   8.4
287 2024-10-02 23:55:00   8.4

[288 rows x 2 columns]
shape cleaned
(288, 2)
18880

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 14:40:00  4.1
1     2024-10-02 14:35:00  4.3
2     2024-10-02 14:30:00  4.6
3     2024-10-02 14:25:00  4.8
4     2024-10-02 14:20:00  5.2
...                   ...  ...
20731 2024-10-02 09:00:00  6.0
20732 2024-10-02 08:55:00  6.0
20733 2024-10-02 08:50:00  6.0
20734 2024-10-02 08:45:00  6.1
20735 2024-10-02 08:40:00  6.0

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00   9.6
1   2024-10-02 00:05:00   9.6
2   2024-10-02 00:10:00   9.9
3   2024-10-02 00:15:00  10.3
4   2024-10-02 00:20:00  10.7
..                  ...   ...
283 2024-10-02 23:35:00  11.0
284 2024-10-02 23:40:00  11.0
285 2024-10-02 23:45:00  10.8
286 2024-10-02 23:50:00  10.4
287 2024-10-02 23:55:00   9.9

[288 rows x 2 columns]
shape cleaned
(288, 2)
19168

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 14:40:00  5.6
1     2024-10-02 14:35:00  5.5
2     2024-10-02 14:30:00  5.5
3     2024-10-02 14:25:00  5.6
4     2024-10-02 14:20:00  5.5
...                   ...  ...
20731 2024-10-02 11:30:00  9.5
20732 2024-10-02 11:25:00  8.8
20733 2024-10-02 11:20:00  8.2
20734 2024-10-02 11:15:00  7.4
20735 2024-10-02 11:10:00  6.8

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  10.4
1   2024-10-02 00:05:00   9.8
2   2024-10-02 00:10:00   9.1
3   2024-10-02 00:15:00   8.6
4   2024-10-02 00:20:00   8.3
..                  ...   ...
283 2024-10-02 23:35:00  11.1
284 2024-10-02 23:40:00  10.9
285 2024-10-02 23:45:00  11.0
286 2024-10-02 23:50:00  10.9
287 2024-10-02 23:55:00  10.8

[288 rows x 2 columns]
shape cleaned
(288, 2)
19456

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 17:10:00  7.6
1     2024-10-02 17:05:00  6.9
2     2024-10-02 17:00:00  6.4
3     2024-10-02 16:55:00  6.3
4     2024-10-02 16:50:00  6.2
...                   ...  ...
20731 2024-10-02 11:30:00  6.7
20732 2024-10-02 11:25:00  6.8
20733 2024-10-02 11:20:00  6.8
20734 2024-10-02 11:15:00  6.7
20735 2024-10-02 11:10:00  6.6

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  11.2
1   2024-10-02 00:05:00  10.8
2   2024-10-02 00:10:00  10.0
3   2024-10-02 00:15:00   9.4
4   2024-10-02 00:20:00   8.4
..                  ...   ...
283 2024-10-02 23:35:00  11.0
284 2024-10-02 23:40:00  11.1
285 2024-10-02 23:45:00  11.1
286 2024-10-02 23:50:00  11.4
287 2024-10-02 23:55:00  11.3

[288 rows x 2 columns]
shape cleaned
(288, 2)
19744

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 17:10:00  3.9
1     2024-10-02 17:05:00  4.1
2     2024-10-02 17:00:00  4.3
3     2024-10-02 16:55:00  4.6
4     2024-10-02 16:50:00  4.8
...                   ...  ...
20731 2024-10-02 11:30:00  6.3
20732 2024-10-02 11:25:00  6.3
20733 2024-10-02 11:20:00  6.2
20734 2024-10-02 11:15:00  6.2
20735 2024-10-02 11:10:00  6.3

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00   8.1
1   2024-10-02 00:05:00   8.9
2   2024-10-02 00:10:00   9.4
3   2024-10-02 00:15:00  10.0
4   2024-10-02 00:20:00  10.7
..                  ...   ...
283 2024-10-02 23:35:00   5.1
284 2024-10-02 23:40:00   5.3
285 2024-10-02 23:45:00   5.5
286 2024-10-02 23:50:00   5.9
287 2024-10-02 23:55:00   7.1

[288 rows x 2 columns]
shape cleaned
(288, 2)
20032

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 17:10:00  5.7
1     2024-10-02 17:05:00  5.3
2     2024-10-02 17:00:00  5.1
3     2024-10-02 16:55:00  5.0
4     2024-10-02 16:50:00  5.0
...                   ...  ...
20731 2024-10-02 11:30:00  6.9
20732 2024-10-02 11:25:00  7.3
20733 2024-10-02 11:20:00  7.6
20734 2024-10-02 11:15:00  7.9
20735 2024-10-02 11:10:00  8.2

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  11.4
1   2024-10-02 00:05:00  11.4
2   2024-10-02 00:10:00  11.4
3   2024-10-02 00:15:00  11.3
4   2024-10-02 00:20:00  11.3
..                  ...   ...
283 2024-10-02 23:35:00  11.3
284 2024-10-02 23:40:00  11.0
285 2024-10-02 23:45:00  10.9
286 2024-10-02 23:50:00  11.0
287 2024-10-02 23:55:00  11.2

[288 rows x 2 columns]
shape cleaned
(288, 2)
20320

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 17:10:00  5.5
1     2024-10-02 17:05:00  5.4
2     2024-10-02 17:00:00  5.4
3     2024-10-02 16:55:00  5.6
4     2024-10-02 16:50:00  6.2
...                   ...  ...
20731 2024-10-02 14:55:00  4.4
20732 2024-10-02 14:50:00  4.6
20733 2024-10-02 14:45:00  5.0
20734 2024-10-02 14:40:00  5.4
20735 2024-10-02 14:35:00  5.5

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  NaN
1   2024-10-02 00:05:00  NaN
2   2024-10-02 00:10:00  NaN
3   2024-10-02 00:15:00  NaN
4   2024-10-02 00:20:00  NaN
..                  ...  ...
283 2024-10-02 23:35:00  6.4
284 2024-10-02 23:40:00  6.4
285 2024-10-02 23:45:00  6.4
286 2024-10-02 23:50:00  6.4
287 2024-10-02 23:55:00  6.4

[288 rows x 2 columns]
shape cleaned
(288, 2)
20608

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 20:35:00   9.4
1     2024-10-02 20:30:00   9.4
2     2024-10-02 20:25:00   9.5
3     2024-10-02 20:20:00   9.6
4     2024-10-02 20:15:00   9.5
...                   ...   ...
20731 2024-10-02 14:55:00  10.7
20732 2024-10-02 14:50:00  10.5
20733 2024-10-02 14:45:00  10.3
20734 2024-10-02 14:40:00  10.5
20735 2024-10-02 14:35:00  10.9

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  8.4
1   2024-10-02 00:05:00  8.4
2   2024-10-02 00:10:00  8.5
3   2024-10-02 00:15:00  8.6
4   2024-10-02 00:20:00  8.5
..                  ...  ...
283 2024-10-02 23:35:00  8.9
284 2024-10-02 23:40:00  8.9
285 2024-10-02 23:45:00  8.8
286 2024-10-02 23:50:00  8.7
287 2024-10-02 23:55:00  8.4

[288 rows x 2 columns]
shape cleaned
(288, 2)
20896

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 20:35:00  5.2
1     2024-10-02 20:30:00  5.0
2     2024-10-02 20:25:00  4.9
3     2024-10-02 20:20:00  5.0
4     2024-10-02 20:15:00  5.1
...                   ...  ...
20731 2024-10-02 14:55:00  5.7
20732 2024-10-02 14:50:00  5.8
20733 2024-10-02 14:45:00  5.9
20734 2024-10-02 14:40:00  5.8
20735 2024-10-02 14:35:00  5.9

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  7.3
1   2024-10-02 00:05:00  7.4
2   2024-10-02 00:10:00  7.6
3   2024-10-02 00:15:00  8.0
4   2024-10-02 00:20:00  8.0
..                  ...  ...
283 2024-10-02 23:35:00  7.4
284 2024-10-02 23:40:00  7.5
285 2024-10-02 23:45:00  7.5
286 2024-10-02 23:50:00  7.5
287 2024-10-02 23:55:00  7.5

[288 rows x 2 columns]
shape cleaned
(288, 2)
21184

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 20:35:00  6.2
1     2024-10-02 20:30:00  5.3
2     2024-10-02 20:25:00  4.6
3     2024-10-02 20:20:00  4.3
4     2024-10-02 20:15:00  4.4
...                   ...  ...
20731 2024-10-02 14:55:00  2.9
20732 2024-10-02 14:50:00  2.8
20733 2024-10-02 14:45:00  2.9
20734 2024-10-02 14:40:00  3.1
20735 2024-10-02 14:35:00  3.3

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00   8.9
1   2024-10-02 00:05:00   8.5
2   2024-10-02 00:10:00   8.5
3   2024-10-02 00:15:00   8.6
4   2024-10-02 00:20:00   8.5
..                  ...   ...
283 2024-10-02 23:35:00  10.2
284 2024-10-02 23:40:00  10.3
285 2024-10-02 23:45:00  10.2
286 2024-10-02 23:50:00   9.9
287 2024-10-02 23:55:00   9.2

[288 rows x 2 columns]
shape cleaned
(288, 2)
21472

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 20:35:00  5.0
1     2024-10-02 20:30:00  4.8
2     2024-10-02 20:25:00  4.7
3     2024-10-02 20:20:00  4.6
4     2024-10-02 20:15:00  4.7
...                   ...  ...
20731 2024-10-02 14:55:00  6.7
20732 2024-10-02 14:50:00  6.7
20733 2024-10-02 14:45:00  6.7
20734 2024-10-02 14:40:00  6.7
20735 2024-10-02 14:35:00  6.8

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  6.9
1   2024-10-02 00:05:00  6.9
2   2024-10-02 00:10:00  6.9
3   2024-10-02 00:15:00  7.0
4   2024-10-02 00:20:00  7.1
..                  ...  ...
283 2024-10-02 23:35:00  7.3
284 2024-10-02 23:40:00  7.3
285 2024-10-02 23:45:00  7.2
286 2024-10-02 23:50:00  7.0
287 2024-10-02 23:55:00  7.0

[288 rows x 2 columns]
shape cleaned
(288, 2)
21760

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 20:35:00  8.1
1     2024-10-02 20:30:00  6.9
2     2024-10-02 20:25:00  6.4
3     2024-10-02 20:20:00  6.1
4     2024-10-02 20:15:00  6.0
...                   ...  ...
20731 2024-10-02 14:55:00  7.3
20732 2024-10-02 14:50:00  7.1
20733 2024-10-02 14:45:00  6.9
20734 2024-10-02 14:40:00  6.5
20735 2024-10-02 14:35:00  6.3

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  5.8
1   2024-10-02 00:05:00  5.8
2   2024-10-02 00:10:00  5.8
3   2024-10-02 00:15:00  5.9
4   2024-10-02 00:20:00  6.0
..                  ...  ...
283 2024-10-02 23:35:00  4.8
284 2024-10-02 23:40:00  5.0
285 2024-10-02 23:45:00  5.3
286 2024-10-02 23:50:00  5.6
287 2024-10-02 23:55:00  5.8

[288 rows x 2 columns]
shape cleaned
(288, 2)
22048

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 20:35:00  11.3
1     2024-10-02 20:30:00  11.4
2     2024-10-02 20:25:00  11.3
3     2024-10-02 20:20:00  11.5
4     2024-10-02 20:15:00  11.4
...                   ...   ...
20731 2024-10-02 14:55:00   6.3
20732 2024-10-02 14:50:00   6.0
20733 2024-10-02 14:45:00   5.8
20734 2024-10-02 14:40:00   5.7
20735 2024-10-02 14:35:00   5.7

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  12.3
1   2024-10-02 00:05:00  12.3
2   2024-10-02 00:10:00  11.8
3   2024-10-02 00:15:00  11.5
4   2024-10-02 00:20:00  11.2
..                  ...   ...
283 2024-10-02 23:35:00  13.5
284 2024-10-02 23:40:00  13.3
285 2024-10-02 23:45:00  13.3
286 2024-10-02 23:50:00  13.2
287 2024-10-02 23:55:00  12.8

[288 rows x 2 columns]
shape cleaned
(288, 2)
22336

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 20:35:00  4.3
1     2024-10-02 20:30:00  4.2
2     2024-10-02 20:25:00  4.3
3     2024-10-02 20:20:00  4.2
4     2024-10-02 20:15:00  4.3
...                   ...  ...
20731 2024-10-02 06:35:00  8.1
20732 2024-10-02 06:30:00  8.4
20733 2024-10-02 06:25:00  8.5
20734 2024-10-02 06:20:00  8.5
20735 2024-10-02 06:15:00  8.3

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  4.9
1   2024-10-02 00:05:00  4.6
2   2024-10-02 00:10:00  4.4
3   2024-10-02 00:15:00  4.6
4   2024-10-02 00:20:00  4.9
..                  ...  ...
283 2024-10-02 23:35:00  7.9
284 2024-10-02 23:40:00  4.8
285 2024-10-02 23:45:00  5.0
286 2024-10-02 23:50:00  5.0
287 2024-10-02 23:55:00  7.8

[288 rows x 2 columns]
shape cleaned
(288, 2)
22624

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 12:15:00  8.0
1     2024-10-02 12:10:00  8.3
2     2024-10-02 12:05:00  8.3
3     2024-10-02 12:00:00  8.3
4     2024-10-02 11:55:00  8.3
...                   ...  ...
20731 2024-10-02 06:35:00  6.1
20732 2024-10-02 06:30:00  6.0
20733 2024-10-02 06:25:00  6.1
20734 2024-10-02 06:20:00  6.0
20735 2024-10-02 06:15:00  6.1

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  4.5
1   2024-10-02 00:05:00  4.2
2   2024-10-02 00:10:00  4.2
3   2024-10-02 00:15:00  4.2
4   2024-10-02 00:20:00  4.2
..                  ...  ...
283 2024-10-02 23:35:00  5.8
284 2024-10-02 23:40:00  5.9
285 2024-10-02 23:45:00  5.8
286 2024-10-02 23:50:00  5.5
287 2024-10-02 23:55:00  5.1

[288 rows x 2 columns]
shape cleaned
(288, 2)
22912

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 12:15:00  6.7
1     2024-10-02 12:10:00  6.4
2     2024-10-02 12:05:00  6.2
3     2024-10-02 12:00:00  6.0
4     2024-10-02 11:55:00  5.7
...                   ...  ...
20731 2024-10-02 06:35:00  6.0
20732 2024-10-02 06:30:00  6.3
20733 2024-10-02 06:25:00  6.5
20734 2024-10-02 06:20:00  6.5
20735 2024-10-02 06:15:00  6.7

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  9.5
1   2024-10-02 00:05:00  9.5
2   2024-10-02 00:10:00  9.4
3   2024-10-02 00:15:00  9.3
4   2024-10-02 00:20:00  9.0
..                  ...  ...
283 2024-10-02 23:35:00  9.2
284 2024-10-02 23:40:00  9.3
285 2024-10-02 23:45:00  9.4
286 2024-10-02 23:50:00  9.4
287 2024-10-02 23:55:00  9.4

[288 rows x 2 columns]
shape cleaned
(288, 2)
23200

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 12:15:00   5.9
1     2024-10-02 12:10:00   6.7
2     2024-10-02 12:05:00   7.5
3     2024-10-02 12:00:00   8.4
4     2024-10-02 11:55:00   9.0
...                   ...   ...
20731 2024-10-02 06:35:00  16.4
20732 2024-10-02 06:30:00  16.1
20733 2024-10-02 06:25:00  16.1
20734 2024-10-02 06:20:00  16.0
20735 2024-10-02 06:15:00  16.1

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00   9.8
1   2024-10-02 00:05:00  10.3
2   2024-10-02 00:10:00  10.8
3   2024-10-02 00:15:00  11.3
4   2024-10-02 00:20:00  11.4
..                  ...   ...
283 2024-10-02 23:35:00   8.5
284 2024-10-02 23:40:00   8.8
285 2024-10-02 23:45:00   9.0
286 2024-10-02 23:50:00   9.5
287 2024-10-02 23:55:00  10.0

[288 rows x 2 columns]
shape cleaned
(288, 2)
23488

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 12:15:00  15.0
1     2024-10-02 12:10:00  15.5
2     2024-10-02 12:05:00  15.8
3     2024-10-02 12:00:00  16.2
4     2024-10-02 11:55:00  16.2
...                   ...   ...
20731 2024-10-02 06:35:00  12.5
20732 2024-10-02 06:30:00  12.7
20733 2024-10-02 06:25:00  12.6
20734 2024-10-02 06:20:00  12.7
20735 2024-10-02 06:15:00  13.0

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  14.7
1   2024-10-02 00:05:00  14.8
2   2024-10-02 00:10:00  15.1
3   2024-10-02 00:15:00  15.6
4   2024-10-02 00:20:00  15.6
..                  ...   ...
283 2024-10-02 23:35:00  15.5
284 2024-10-02 23:40:00  15.3
285 2024-10-02 23:45:00  15.0
286 2024-10-02 23:50:00  14.7
287 2024-10-02 23:55:00  14.6

[288 rows x 2 columns]
shape cleaned
(288, 2)
23776

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 12:15:00  8.4
1     2024-10-02 12:10:00  8.5
2     2024-10-02 12:05:00  8.5
3     2024-10-02 12:00:00  8.2
4     2024-10-02 11:55:00  8.2
...                   ...  ...
20731 2024-10-02 06:35:00  5.2
20732 2024-10-02 06:30:00  5.0
20733 2024-10-02 06:25:00  4.8
20734 2024-10-02 06:20:00  4.7
20735 2024-10-02 06:15:00  4.9

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  5.7
1   2024-10-02 00:05:00  5.5
2   2024-10-02 00:10:00  5.1
3   2024-10-02 00:15:00  4.8
4   2024-10-02 00:20:00  4.7
..                  ...  ...
283 2024-10-02 23:35:00  5.4
284 2024-10-02 23:40:00  5.5
285 2024-10-02 23:45:00  5.6
286 2024-10-02 23:50:00  5.7
287 2024-10-02 23:55:00  5.7

[288 rows x 2 columns]
shape cleaned
(288, 2)
24064

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 12:15:00  5.4
1     2024-10-02 12:10:00  5.5
2     2024-10-02 12:05:00  5.6
3     2024-10-02 12:00:00  5.7
4     2024-10-02 11:55:00  5.8
...                   ...  ...
20731 2024-10-02 06:35:00  8.2
20732 2024-10-02 06:30:00  8.3
20733 2024-10-02 06:25:00  8.3
20734 2024-10-02 06:20:00  8.3
20735 2024-10-02 06:15:00  8.3

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00   8.4
1   2024-10-02 00:05:00   9.3
2   2024-10-02 00:10:00  10.2
3   2024-10-02 00:15:00  10.9
4   2024-10-02 00:20:00  11.9
..                  ...   ...
283 2024-10-02 23:35:00   4.5
284 2024-10-02 23:40:00   4.8
285 2024-10-02 23:45:00   5.3
286 2024-10-02 23:50:00   6.5
287 2024-10-02 23:55:00   7.8

[288 rows x 2 columns]
shape cleaned
(288, 2)
24352

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 12:15:00  6.9
1     2024-10-02 12:10:00  7.0
2     2024-10-02 12:05:00  7.0
3     2024-10-02 12:00:00  7.0
4     2024-10-02 11:55:00  7.0
...                   ...  ...
20731 2024-10-02 11:25:00  6.9
20732 2024-10-02 11:20:00  6.5
20733 2024-10-02 11:15:00  6.5
20734 2024-10-02 11:10:00  6.4
20735 2024-10-02 11:05:00  6.2

[20736 rows x 2 columns]
                   time    bg
0   2024-10-02 00:00:00  10.8
1   2024-10-02 00:05:00  11.0
2   2024-10-02 00:10:00  10.9
3   2024-10-02 00:15:00  10.7
4   2024-10-02 00:20:00  11.0
..                  ...   ...
283 2024-10-02 23:35:00  10.1
284 2024-10-02 23:40:00  10.2
285 2024-10-02 23:45:00  10.1
286 2024-10-02 23:50:00  10.2
287 2024-10-02 23:55:00  10.5

[288 rows x 2 columns]
shape cleaned
(288, 2)
24640

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time    bg
0     2024-10-02 17:05:00  11.3
1     2024-10-02 17:00:00  10.8
2     2024-10-02 16:55:00  10.0
3     2024-10-02 16:50:00   9.4
4     2024-10-02 16:45:00   8.6
...                   ...   ...
20731 2024-10-02 11:25:00   6.0
20732 2024-10-02 11:20:00   6.0
20733 2024-10-02 11:15:00   5.9
20734 2024-10-02 11:10:00   5.9
20735 2024-10-02 11:05:00   5.9

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  9.8
1   2024-10-02 00:05:00  9.7
2   2024-10-02 00:10:00  9.7
3   2024-10-02 00:15:00  9.5
4   2024-10-02 00:20:00  9.3
..                  ...  ...
283 2024-10-02 23:35:00  9.8
284 2024-10-02 23:40:00  9.8
285 2024-10-02 23:45:00  9.7
286 2024-10-02 23:50:00  9.8
287 2024-10-02 23:55:00  9.9

[288 rows x 2 columns]
shape cleaned
(288, 2)
24928

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                     time   bg
0     2024-10-02 17:05:00  8.0
1     2024-10-02 17:00:00  8.0
2     2024-10-02 16:55:00  7.9
3     2024-10-02 16:50:00  8.0
4     2024-10-02 16:45:00  8.1
...                   ...  ...
20731 2024-10-02 11:25:00  3.0
20732 2024-10-02 11:20:00  3.1
20733 2024-10-02 11:15:00  3.3
20734 2024-10-02 11:10:00  3.5
20735 2024-10-02 11:05:00  3.8

[20736 rows x 2 columns]
                   time   bg
0   2024-10-02 00:00:00  8.2
1   2024-10-02 00:05:00  8.5
2   2024-10-02 00:10:00  8.9
3   2024-10-02 00:15:00  9.2
4   2024-10-02 00:20:00  9.5
..                  ...  ...
283 2024-10-02 23:35:00  4.9
284 2024-10-02 23:40:00  5.3
285 2024-10-02 23:45:00  5.9
286 2024-10-02 23:50:00  6.8
287 2024-10-02 23:55:00  7.8

[288 rows x 2 columns]
shape cleaned
(288, 2)
25216

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')
C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

                    time    bg
0    2024-10-02 17:05:00   7.8
1    2024-10-02 17:00:00   7.9
2    2024-10-02 16:55:00   7.8
3    2024-10-02 16:50:00   7.8
4    2024-10-02 16:45:00   7.7
...                  ...   ...
5971 2024-10-02 18:20:00  10.1
5972 2024-10-02 18:15:00  10.3
5973 2024-10-02 18:10:00  10.4
5974 2024-10-02 18:05:00  10.2
5975 2024-10-02 18:00:00   9.8

[5976 rows x 2 columns]
                   time    bg
0   2024-10-02 11:10:00   3.5
1   2024-10-02 11:15:00   3.3
2   2024-10-02 11:20:00   3.1
3   2024-10-02 11:25:00   3.0
4   2024-10-02 11:30:00   2.8
..                  ...   ...
149 2024-10-02 23:35:00   9.8
150 2024-10-02 23:40:00  10.3
151 2024-10-02 23:45:00  10.7
152 2024-10-02 23:50:00  11.0
153 2024-10-02 23:55:00  11.6

[154 rows x 2 columns]
shape cleaned
(154, 2)

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')

In [39]:
day_two

,p_num,time,bg-5:55,bg-5:50,bg-5:45,bg-5:40,bg-5:35,bg-5:30,bg-5:25,bg-5:20,...,bg-0:40,bg-0:35,bg-0:30,bg-0:25,bg-0:20,bg-0:15,bg-0:10,bg-0:05,bg-0:00,bg+1:00
0,p12,00:00:00,6.0,6.0,6.1,6.1,6.0,6.1,6.1,6.0,...,10.9,11.0,11.3,11.7,11.9,12.5,13.0,13.5,13.8,10.2
1,p12,00:05:00,6.0,6.1,6.1,6.0,6.1,6.1,6.0,6.1,...,11.0,11.3,11.7,11.9,12.5,13.0,13.5,13.8,13.9,10.0
2,p12,00:10:00,6.1,6.1,6.0,6.1,6.1,6.0,6.1,6.1,...,11.3,11.7,11.9,12.5,13.0,13.5,13.8,13.9,13.7,10.0
3,p12,00:15:00,6.1,6.0,6.1,6.1,6.0,6.1,6.1,6.1,...,11.7,11.9,12.5,13.0,13.5,13.8,13.9,13.7,13.5,10.3
4,p12,00:20:00,6.0,6.1,6.1,6.0,6.1,6.1,6.1,6.0,...,11.9,12.5,13.0,13.5,13.8,13.9,13.7,13.5,13.3,10.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
571,p12,23:35:00,4.8,5.0,5.2,5.2,5.2,5.2,5.2,5.3,...,6.6,6.5,6.5,6.5,6.4,6.4,6.4,6.4,6.7,10.6
572,p12,23:40:00,5.0,5.2,5.2,5.2,5.2,5.2,5.3,5.4,...,6.5,6.5,6.5,6.4,6.4,6.4,6.4,6.7,7.3,10.2
573,p12,23:45:00,5.2,5.2,5.2,5.2,5.2,5.3,5.4,5.4,...,6.5,6.5,6.4,6.4,6.4,6.4,6.7,7.3,7.5,10.0
574,p12,23:50:00,5.2,5.2,5.2,5.2,5.3,5.4,5.4,5.4,...,6.5,6.4,6.4,6.4,6.4,6.7,7.3,7.5,7.9,10.0
575,p12,23:55:00,5.2,5.2,5.2,5.3,5.4,5.4,5.4,5.4,...,6.4,6.4,6.4,6.4,6.7,7.3,7.5,7.9,8.8,10.0

In [10]:
day_two

,p_num,time,bg-5:55,bg-5:50,bg-5:45,bg-5:40,bg-5:35,bg-5:30,bg-5:25,bg-5:20,...,bg-0:40,bg-0:35,bg-0:30,bg-0:25,bg-0:20,bg-0:15,bg-0:10,bg-0:05,bg-0:00,bg+1:00
0,p12,00:00:00,6.0,6.0,6.1,6.1,6.0,6.1,6.1,6.0,...,10.9,11.0,11.3,11.7,11.9,12.5,13.0,13.5,13.8,10.2
1,p12,00:05:00,6.0,6.1,6.1,6.0,6.1,6.1,6.0,6.1,...,11.0,11.3,11.7,11.9,12.5,13.0,13.5,13.8,13.9,10.0
2,p12,00:10:00,6.1,6.1,6.0,6.1,6.1,6.0,6.1,6.1,...,11.3,11.7,11.9,12.5,13.0,13.5,13.8,13.9,13.7,10.0
3,p12,00:15:00,6.1,6.0,6.1,6.1,6.0,6.1,6.1,6.1,...,11.7,11.9,12.5,13.0,13.5,13.8,13.9,13.7,13.5,10.3
4,p12,00:20:00,6.0,6.1,6.1,6.0,6.1,6.1,6.1,6.0,...,11.9,12.5,13.0,13.5,13.8,13.9,13.7,13.5,13.3,10.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,p12,23:35:00,15.7,15.1,15.0,15.1,15.1,15.1,15.3,15.3,...,3.9,4.1,4.2,4.3,4.3,4.2,4.4,4.8,5.0,6.0
284,p12,23:40:00,15.1,15.0,15.1,15.1,15.1,15.3,15.3,15.0,...,4.1,4.2,4.3,4.3,4.2,4.4,4.8,5.0,5.0,6.2
285,p12,23:45:00,15.0,15.1,15.1,15.1,15.3,15.3,15.0,14.9,...,4.2,4.3,4.3,4.2,4.4,4.8,5.0,5.0,5.0,6.3
286,p12,23:50:00,15.1,15.1,15.1,15.3,15.3,15.0,14.9,15.0,...,4.3,4.3,4.2,4.4,4.8,5.0,5.0,5.0,4.9,6.2
287,p12,23:55:00,15.1,15.1,15.3,15.3,15.0,14.9,15.0,14.8,...,4.3,4.2,4.4,4.8,5.0,5.0,5.0,4.9,4.8,6.4

In [21]:
from utils import transform_into_ts_preserved
transformed = transform_into_ts_preserved(day_two)

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:104: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, new_row], ignore_index=True)

In [23]:
transformed

                     time    bg
0     2024-10-02 00:00:00  13.8
1     2024-10-02 23:55:00  13.5
2     2024-10-02 23:50:00  13.0
3     2024-10-02 23:45:00  12.5
4     2024-10-02 23:40:00  11.9
...                   ...   ...
20731 2024-10-02 18:20:00  15.0
20732 2024-10-02 18:15:00  15.3
20733 2024-10-02 18:10:00  15.3
20734 2024-10-02 18:05:00  15.1
20735 2024-10-02 18:00:00  15.1

[20736 rows x 2 columns]

In [25]:
from utils import remove_redundancy

cleaned_df = remove_redundancy(transformed)
print(cleaned_df)

                   time    bg
0   2024-10-02 00:00:00  13.8
1   2024-10-02 00:05:00  13.9
2   2024-10-02 00:10:00  13.7
3   2024-10-02 00:15:00  13.5
4   2024-10-02 00:20:00  13.3
..                  ...   ...
283 2024-10-02 23:35:00  11.7
284 2024-10-02 23:40:00  11.9
285 2024-10-02 23:45:00  12.5
286 2024-10-02 23:50:00  13.0
287 2024-10-02 23:55:00  13.5

[288 rows x 2 columns]

C:\Users\Administrator\Desktop\raphi_other\repositories\ts\src\utils.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['bg'] = df['bg'].fillna(method='ffill')